sudo: required
services:
  - docker

before_install:
  - docker build -t asif/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run asif/react-test npm test -- --coverage
  #- docker run -e CI=true asif/react-test npm test

after_success:
  - docker build -t asif/multi-client ./client
  - docker build -t asif/multi-nginx ./nginx
  - docker build -t asif/multi-server ./server
  - docker build -t asif/multi-worker ./worker

  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #Take thos images and push them to docker hub
  - docker push asif/multi-client
  - docker push asif/multi-nginx
  - docker push asif/multi-server
  - docker push asif/multi-worker


